renovate: add support for git-submodules

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -19,9 +19,22 @@ on:
       - 'docs/**'
 
 jobs:
+  detect-changes:
+    runs-on: ubuntu-24.04
+    outputs:
+      changed: ${{ steps.set-output.outputs.changed }}
+    steps:
+      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
+        with:
+          fetch-depth: 0
+      - id: set-output
+        run: |
+          echo "::set-output name=changed::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^(scripts/)' | wc -l)"
+
   lint:
-    runs-on: ubuntu-latest
-    if: "!contains(github.event.head_commit.message, '[ci skip]')"
+    runs-on: ubuntu-24.04
+    needs: detect-changes
+    if: "(needs.detect-changes.outputs.changed != '0' || github.event_name == 'push')"
     steps:
       - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
       - name: Run the sh-checker
@@ -50,57 +63,57 @@ jobs:
     container: ${{ matrix.container }}
     env:
       HELM_SECRETS_WINDOWS_SHELL: ${{ matrix.shell == 'wsl' && 'wsl' || 'bash' }}
-    if: "!contains(github.event.head_commit.message, '[ci skip]')"
+    if: "(needs.detect-changes.outputs.changed != '0' || github.event_name == 'push')"
     timeout-minutes: 20
     strategy:
       fail-fast: false
       matrix:
-        os: [ubuntu-latest]
+        os: [ubuntu-24.04]
         container: [""]
         shell: [dash]
         jobs: [4]
         helm-version: [""]
         include:
-          - os: windows-latest
+          - os: windows-24.04
             shell: bash
             jobs: 1
-          - os: windows-latest
+          - os: windows-24.04
             shell: cygwin
             jobs: 1
-          - os: windows-latest
+          - os: windows-24.04
             shell: wsl
             jobs: 4
-          - os: macos-latest
+          - os: macos-24.04
             shell: bash 3.2
             jobs: 4
-          - os: macos-latest
+          - os: macos-24.04
             shell: bash 3.2 with coreutils
             jobs: 4
-          #- os: ubuntu-latest
+          #- os: ubuntu-24.04
           #  container: centos:7
           #  shell: bash 4.2
           #  jobs: 4
-          - os: ubuntu-latest
+          - os: ubuntu-24.04
             container: registry.access.redhat.com/ubi8/ubi-minimal
             shell: bash 4.4
             jobs: 4
-          - os: ubuntu-latest
+          - os: ubuntu-24.04
             shell: bash
             jobs: 4
             helm-version: 3.9.4
-          - os: ubuntu-latest
+          - os: ubuntu-24.04
             shell: bash
             jobs: 4
             helm-version: 3.16.4
-          - os: ubuntu-latest
+          - os: ubuntu-24.04
             container: alpine
             shell: zsh
             jobs: 4
-          - os: ubuntu-latest
+          - os: ubuntu-24.04
             container: alpine
             shell: ash
             jobs: 4
-          - os: ubuntu-latest
+          - os: ubuntu-24.04
             container: ubuntu:22.04
             shell: posh
             jobs: 4
@@ -143,7 +156,7 @@ jobs:
         run: |-
           git config --global core.autocrlf false
           git config --global core.eol lf
-        if: "contains(matrix.os, 'windows-latest')"
+        if: "contains(matrix.os, 'windows-24.04')"
 
       # this is to fix https://github.com/actions/checkout/issues/760
       - run: git config --global --add safe.directory /__w/helm-secrets/helm-secrets
@@ -188,7 +201,7 @@ jobs:
           echo "/usr/local/opt/coreutils/libexec/gnubin" >> $GITHUB_PATH
 
       - name: Setup parallel (mac OS)
-        if: "contains(matrix.os, 'macos-latest')"
+        if: "contains(matrix.os, 'macos-24.04')"
         run: brew install parallel
 
       - name: Setup parallel (WSL)
@@ -239,8 +252,8 @@ jobs:
           retention-days: 1
 
   coverage:
-    runs-on: ubuntu-latest
-    if: "!contains(github.event.head_commit.message, '[ci skip]')"
+    runs-on: ubuntu-24.04
+    if: "(needs.detect-changes.outputs.changed != '0' || github.event_name == 'push')"
     env:
       BATSLIB_TEMP_PRESERVE: "0"
       BATSLIB_TEMP_PRESERVE_ON_FAILURE: "0"
@@ -320,12 +333,12 @@ jobs:
           CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
 
   integration-tests:
-    runs-on: ubuntu-latest
-    if: "!contains(github.event.head_commit.message, '[ci skip]')"
+    runs-on: ubuntu-24.04
+    if: "(needs.detect-changes.outputs.changed != '0' || github.event_name == 'push')"
     strategy:
       fail-fast: false
       matrix:
-        os: [ubuntu-latest]
+        os: [ubuntu-24.04]
         container: [""]
         shell: [dash]
         jobs: [4]
@@ -379,7 +392,7 @@ jobs:
           if-no-files-found: error
 
   report:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-24.04
     if: always()
     needs:
       - unit-tests
@@ -394,3 +407,16 @@ jobs:
         with:
           report_paths: '**/TEST-*.xml'
           detailed_summary: true
+
+  fail:
+    if: "${{ cancelled() || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure') }}"
+    needs:
+      - "lint"
+      - "report"
+      - "coverage"
+    runs-on: "ubuntu-24.04"
+    steps:
+      - name: "verify checks passed"
+        run: |
+          echo "Some checks have failed!"
+          exit 1
